"""
Gap estimation and handling utilities.

Handles uniform spacing (gaps) between photos and page edges.
"""

from typing import List, Dict, Any


def estimate_gap(photos: List[Dict[str, Any]], page_width: float, page_height: float) -> float:
    """
    Estimate the average gap between adjacent photos.
    
    Analyzes photo positions to detect uniform spacing. Returns the average
    gap found between horizontally and vertically adjacent photos, and between
    photos and page edges.
    
    Args:
        photos: List of photo dicts with area_left, area_top, area_width, area_height.
        page_width: Page width in MCF units.
        page_height: Page height in MCF units.
    
    Returns:
        Estimated gap in MCF units (0.1mm). Returns 0.0 if no clear gap detected
        or if there are too few photos to estimate reliably.
    """
    if not photos:
        return 0.0
    
    gaps = []
    
    # Sort photos for edge detection
    sorted_by_left = sorted(photos, key=lambda p: p.get('area_left', 0))
    sorted_by_top = sorted(photos, key=lambda p: p.get('area_top', 0))
    
    # Check left edge gaps (photos near x=0)
    for p in sorted_by_left[:3]:  # Check first few photos
        left = p.get('area_left', 0)
        if left > 0 and left < page_width * 0.1:  # Within 10% of left edge
            gaps.append(left)
    
    # Check top edge gaps (photos near y=0)
    for p in sorted_by_top[:3]:
        top = p.get('area_top', 0)
        if top > 0 and top < page_height * 0.1:
            gaps.append(top)
    
    # Check horizontal adjacency (photos side-by-side)
    for i, p1 in enumerate(photos):
        left1 = p1.get('area_left', 0)
        top1 = p1.get('area_top', 0)
        width1 = p1.get('area_width', 0)
        height1 = p1.get('area_height', 0)
        right1 = left1 + width1
        
        for p2 in photos[i+1:]:
            left2 = p2.get('area_left', 0)
            top2 = p2.get('area_top', 0)
            height2 = p2.get('area_height', 0)
            
            # Check if p2 is to the right of p1 and vertically overlapping
            vertical_overlap = not (top1 + height1 <= top2 or top2 + height2 <= top1)
            if vertical_overlap and left2 > right1:
                gap = left2 - right1
                if 0 < gap < page_width * 0.05:  # Reasonable gap (< 5% of page)
                    gaps.append(gap)
    
    # Check vertical adjacency (photos stacked)
    for i, p1 in enumerate(photos):
        left1 = p1.get('area_left', 0)
        top1 = p1.get('area_top', 0)
        width1 = p1.get('area_width', 0)
        height1 = p1.get('area_height', 0)
        bottom1 = top1 + height1
        
        for p2 in photos[i+1:]:
            left2 = p2.get('area_left', 0)
            top2 = p2.get('area_top', 0)
            width2 = p2.get('area_width', 0)
            
            # Check if p2 is below p1 and horizontally overlapping
            horizontal_overlap = not (left1 + width1 <= left2 or left2 + width2 <= left1)
            if horizontal_overlap and top2 > bottom1:
                gap = top2 - bottom1
                if 0 < gap < page_height * 0.05:
                    gaps.append(gap)
    
    if not gaps:
        return 0.0
    
    # Return median gap (more robust than mean for outliers)
    gaps.sort()
    n = len(gaps)
    if n % 2 == 0:
        return (gaps[n//2 - 1] + gaps[n//2]) / 2.0
    else:
        return gaps[n//2]


def apply_gap_to_layout(page_width: float, page_height: float, 
                       photos: List[Dict[str, Any]], gap: float) -> List[Dict[str, Any]]:
    """
    Apply uniform gap to a layout by adjusting photo positions and sizes.
    
    This is used to add gaps to a layout generated by an algorithm that doesn't
    know about gaps. Each photo's position is increased by gap, and size is
    decreased by gap.
    
    Args:
        page_width: Page width in MCF units.
        page_height: Page height in MCF units.
        photos: List of photo dicts to adjust.
        gap: Gap value in MCF units.
    
    Returns:
        New list of photo dicts with adjusted positions/sizes.
    """
    if gap <= 0:
        return photos
    
    adjusted = []
    for p in photos:
        adj = p.copy()
        
        # Increase position by gap (margin from edges and other photos)
        adj['area_left'] = p.get('area_left', 0) + gap
        adj['area_top'] = p.get('area_top', 0) + gap
        
        # Decrease size by gap (to create spacing between photos)
        adj['area_width'] = max(0, p.get('area_width', 0) - gap)
        adj['area_height'] = max(0, p.get('area_height', 0) - gap)
        
        adjusted.append(adj)
    
    return adjusted


def remove_gap_from_layout(photos: List[Dict[str, Any]], gap: float) -> List[Dict[str, Any]]:
    """
    Remove gap from a layout (inverse of apply_gap_to_layout).
    
    Used before passing photos to an algorithm that should work on gap-free coordinates.
    Each photo's position is decreased by gap, and size is increased by gap.
    
    Args:
        photos: List of photo dicts to adjust.
        gap: Gap value in MCF units.
    
    Returns:
        New list of photo dicts with gap removed.
    """
    if gap <= 0:
        return photos
    
    adjusted = []
    for p in photos:
        adj = p.copy()
        
        # Decrease position by gap
        adj['area_left'] = max(0, p.get('area_left', 0) - gap)
        adj['area_top'] = max(0, p.get('area_top', 0) - gap)
        
        # Increase size by gap
        adj['area_width'] = p.get('area_width', 0) + gap
        adj['area_height'] = p.get('area_height', 0) + gap
        
        adjusted.append(adj)
    
    return adjusted
